server:
  port: 8760

spring:
  application:
    name: hm-eureka-server

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    # 由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务示例,它并不需要去检索服务,所以也设置为false
    fetch-registry: false
    serviceUrl:
      # 使用Eureka服务器进行身份验证
      defaultZone: http://${eureka.instance.hostname}:8760/eureka
  server:
    # [开发环境]关闭eureka自我保护机制false,保证不可用服务及时剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 20000
